theme = "theme"

[editor]
rulers = [80, 100, 120]
cursorline = true
auto-save = true
color-modes = true
bufferline = "multiple"
completion-trigger-len = 1

[editor.indent-guides]
render = true
character = "â”Š"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
V = ["extend_line_below", "select_mode"]
