theme = "mocha"

[editor]
rulers = [120]
cursorline = true
auto-save = true
color-modes = true
bufferline = "multiple"
completion-trigger-len = 1
mouse = false

[editor.whitespace.render]
tab = "all"

[editor.indent-guides]
render = true

[editor.statusline]
separator = "î‚³"
left = ["mode", "spacer", "version-control", "spacer", "file-base-name", "file-modification-indicator"]
right = ["workspace-diagnostics", "spinner", "file-type", "separator", "file-line-ending", "separator", "spacer", "position-percentage", "position"]

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
V = ["extend_line_below", "select_mode"]
