add_newline = false
command_timeout = 1000
scan_timeout = 1000

[aws]
disabled = true
style = "bold #ffb86c"

[battery]
disabled = true

[bun]
disabled = true

[character]
error_symbol = "[✗](bold #ff5555)"
success_symbol = "[➜](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
[git_branch]
style = "bold #ff79c6"
symbol = " "

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[kubernetes]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"
