theme = "catppuccin_mocha"

[editor]
rulers = [81]
auto-format = true
completion-trigger-len = 1
bufferline = "multiple"
cursorline = true
color-modes = true
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-signature-help-docs = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spacer", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "spacer", "position-percentage", "file-type"]
